name: Java do MODOLO

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  COMPILAR:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
   - name: Compilando Java 
      run: |
        cd src
       javac -cp . Teste

 - name: Rodando o Programa
      run: |
        cd src
        java -cp . Teste
    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Deploy Docker image2
      with:
        image: anaclaraz/native_jbs
        tags: 1.0
        registry: docker.io
        dockerfile: dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
