name: Deploy Catraca JBS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: instalando JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Compilando a main
      run: |
            cd src && javac -cp . Main.java
    
    - name: Compilando Classe Teste
      run: |
            cd src && javac -cp . Teste.java
            
    - uses: actions/checkout@v3
      name: Check out code
      
    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Build & push Docker image
      with:
        image: anaclaraz/native_jbs
        tags: ${{ github.run_number }}
        registry: docker.io
        dockerfile: dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password:  ${{ secrets.DOCKER_PASSWORD }}
            

